### ISSUE TITLE
HongKong is a part of China !

### ISSUE THREAD

**Issue by YasinZhou** [freedomhkg/freedomhkgnet#252]
我支持你们游行示威，但是反对一切港独的做法。
一：你要游行可以，你如果破坏公共设施，就不要说什么警察发射催泪弹什么的，所以请理智游行。
二：请注意自己的人身安全，不要做过于危险的动作
三：如果你是跟随在破坏分子身后，请立即远离他，他是有靠山或者一腔热血没头脑，你不是，你还有家人和朋友，你还有未来。
四：请不要再去公共交通的地方，我们都是有家人的，我们需要上班和工作，请不要把你的行为后果强加在别人身上。
五：政府有不对的地方，那就请你做到那个岗位，然后改变这种状况，而不是去分裂国家，你没有武装力量就想分裂国家，在我看来就像是泼妇在撒泼一样，无理取闹。请去改变它，而不是去施展暴力或冷暴力。

**Comment by lifehome** [comment]
謝謝你喔，我先把 Issue 關掉～
如果有需要再聯絡，請到網站 https://freedomhkg.net 尋找聯絡方式。
