### ISSUE TITLE
fix tag buttons

### ISSUE THREAD

**Issue by demopaxlee** [freedomhkg/freedomhkgnet#29]
最底兩個hashtag而家係link去https://freedomhkg.net/# 㩒落去會back to top，一係整走條link一係link去social media?

**Comment by mingchuno** [comment]
就係想知條link係咩 @demopaxlee

**Comment by demopaxlee** [comment]
e.preventDefault or

copy to clipboard or

link to twitter / fb?

**Comment by mingchuno** [comment]
twitter & fb ?

**Comment by demopaxlee** [comment]
great, I'll add a card on trello
